inference_checkpoint_name: None # comment out or set to "None" to run inference from scratch
execute_processing: true       # set to false to skip processing the dataset videos and loading existing processed data
execute_evaluation: false        # set to false to skip calculating evaluation metrics and plotting
execute_rendering: false         # set to false to skip rendering the videos
render_poses_only: true        # set to true to render the pose keypoints overlayed on the black video frames

dataset:
  name: GettingStarted
  code_file: datasets.dataset.Dataset
  video_folder: /datasets/<your-dataset-name>/videos

pose_estimators:
  - name: YoloPose
    enabled: true
    code_file: models.yolo_pose_estimator.YoloPoseEstimator
    config:
      weights: yolo11l-pose.pt
      save_keypoints_in_coco_format: true
      confidence_threshold: 0.3

  - name: MediaPipePose
    enabled: true
    code_file: models.mediapipe_pose_estimator.MediaPipePoseEstimator
    config:
      weights: pose_landmarker_heavy.task
      max_num_poses: 3
      save_keypoints_in_coco_format: true
      confidence_threshold: 0.3

  - name: OpenPose
    enabled: true
    code_file: models.open_pose_estimator.OpenPoseEstimator
    config:
      save_keypoints_in_coco_format: true
      overlay_strategy: BODY_25
      confidence_threshold: 0.15
  
  - name: MaskAnyoneAPI-MediaPipe
    enabled: true
    code_file: models.maskanyone_api_pose_estimator.MaskAnyoneApiPoseEstimator
    config:
      overlay_strategy: mp_pose
      save_keypoints_in_coco_format: true
      confidence_threshold: 0
      chunk_length: 120 # in seconds 

  - name: MaskAnyoneAPI-OpenPose
    enabled: true
    code_file: models.maskanyone_api_pose_estimator.MaskAnyoneApiPoseEstimator
    config:
      overlay_strategy: openpose # uses BODY_25 model
      save_keypoints_in_coco_format: true
      confidence_threshold: 0
      chunk_length: 120 # in seconds 

  - name: MaskAnyoneUI-MediaPipe
    enabled: false
    code_file: models.maskanyone_ui_pose_estimator.MaskAnyoneUiPoseEstimator  
    config:
      dataset_poses_folder: /datasets/ted-talks/maskanyone_ui_mediapipe
      overlay_strategy: mp_pose
      save_keypoints_in_coco_format: true
      confidence_threshold: 0

  - name: MaskAnyoneUI-OpenPose
    enabled: false
    code_file: models.maskanyone_ui_pose_estimator.MaskAnyoneUiPoseEstimator  
    config:
      dataset_poses_folder: /datasets/ted-talks/maskanyone_ui_openpose
      overlay_strategy: openpose # uses BODY_25 model
      save_keypoints_in_coco_format: true
      confidence_threshold: 0

metrics:
  - name: Velocity
    code_file: evaluation.metrics.velocity.VelocityMetric
    config:
      time_unit: frame

  - name: Acceleration
    code_file: evaluation.metrics.acceleration.AccelerationMetric
    config:
      time_unit: frame
  
  - name: Jerk
    code_file: evaluation.metrics.jerk.JerkMetric
    config:
      time_unit: frame

